DELETE FROM FactAtakTerrorystyczny WHERE 1=1;

DELETE FROM DimData WHERE 1=1;

DELETE FROM DimBron WHERE 1=1;

DELETE FROM DimCelAtaku WHERE 1=1;

DELETE FROM DimGrupaTerrorystyczna WHERE 1=1;

DELETE FROM DimLokalizacja WHERE 1=1;

DELETE FROM DimRodzajAtaku WHERE 1=1;